services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./static-site:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana


volumes:
  pgdata:
  grafana-data:
